<#
.SYNOPSIS
    Build and (re)deploy Terra-Cogitia locally on Docker Desktop.

.DESCRIPTION
    Idempotent local deployment -- safe to run repeatedly:
      Phase 1: Prerequisites (Docker engine, compose v2, buildx, sources, registry, secrets)
      Phase 2: Build images  cogitia-database / cogitia-backend / cogitia-frontend
      Phase 3: Runtime configuration (.runtime\cogitia.env + .runtime\secrets\*.env)
      Phase 4: Deploy -- database backup, NetCogitia network, stray-container removal,
               docker compose up (recreates only what changed; data volumes are kept)
      Phase 5: Wait until all three containers report healthy
      Phase 6: Verification (endpoints, database, CORS, NetCogitia connectivity, restart policy)
      Phase 7: Remove dangling Terra-Cogitia images (label-scoped, never global)

    Endpoints:  Front-End http://localhost:8200   Back-End http://localhost:8201
    Only Terra-Cogitia resources are touched (container names, NetCogitia, image label).

.PARAMETER NoCache
    Pass --no-cache to docker build.

.PARAMETER SkipBuild
    Reuse the existing local images (fails if they do not exist).

.PARAMETER SkipBackup
    Do not dump the database before redeploying.

.PARAMETER HealthTimeoutSec
    Maximum wait for healthy containers (default 300).

.PARAMETER RegistryPath
    Alternative registry file (default: cogitia-registry.json next to this script).

.EXAMPLE
    .\deploy-local.ps1
    .\deploy-local.ps1 -NoCache
    .\deploy-local.ps1 -SkipBuild
#>

[CmdletBinding()]
param(
    [switch]$NoCache,
    [switch]$SkipBuild,
    [switch]$SkipBackup,
    [ValidateRange(30, 1800)][int]$HealthTimeoutSec = 300,
    [string]$RegistryPath
)

$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\Cogitia.Common.psm1') -Force -DisableNameChecking

function Invoke-LocalCompose {
    param([string[]]$Arguments)
    $composeArgs = @('compose', '-p', $registry.compose_project,
                     '--project-directory', $runtimeDir,
                     '--env-file', (Join-Path $runtimeDir 'cogitia.env'),
                     '-f', $composeFile) + $Arguments
    Invoke-CogitiaNative docker $composeArgs -DisplayName "docker compose $($Arguments -join ' ')" | Out-Null
}

function Backup-LocalDatabase {
    $db = $registry.services.database
    if ((Get-CogitiaContainerState $db.container_name) -notlike 'running/*') {
        Write-CogitiaInfo "Backup skipped: $($db.container_name) not running (first deployment?)"
        return
    }
    $backupDir = Join-Path (Resolve-CogitiaPath $registry $registry.paths.backup_dir) 'local'
    if (-not (Test-Path $backupDir)) { New-Item -ItemType Directory -Path $backupDir -Force | Out-Null }
    $name = "cogitia_$($registry.database.name)_$(Get-Date -Format 'yyyyMMdd_HHmmss').dump"
    $inContainer = "/tmp/$name"
    # pg_dump inside the container + docker cp: PowerShell pipes would corrupt the binary dump.
    Invoke-CogitiaNative docker @('exec', $db.container_name, 'pg_dump', '-U', $registry.database.user, '-d', $registry.database.name, '-Fc', '-f', $inContainer) -Quiet -DisplayName 'pg_dump' | Out-Null
    Invoke-CogitiaNative docker @('cp', "$($db.container_name):$inContainer", (Join-Path $backupDir $name)) -Quiet -DisplayName 'docker cp (backup)' | Out-Null
    Invoke-CogitiaNative docker @('exec', $db.container_name, 'rm', '-f', $inContainer) -AllowFailure -Quiet | Out-Null
    $sizeKB = [math]::Round((Get-Item (Join-Path $backupDir $name)).Length / 1KB, 1)
    Write-CogitiaOk "Database backup: $(Join-Path $backupDir $name) ($sizeKB KB)"
    Get-ChildItem $backupDir -Filter 'cogitia_*.dump' | Sort-Object LastWriteTime -Descending | Select-Object -Skip 5 | Remove-Item -Force
}

$exitCode = 0
$overallStart = Get-Date
try {
    Write-CogitiaBanner 'Terra-Cogitia -- Local Deployment (Docker Desktop)'

    # --- Phase 1: Prerequisites ------------------------------------------------
    Write-CogitiaPhase 'PHASE 1: Prerequisites'
    $registry = if ($RegistryPath) { Get-CogitiaRegistry -Path $RegistryPath } else { Get-CogitiaRegistry }
    $envCfg = Get-CogitiaEnvironment $registry 'local'
    $docker = Assert-CogitiaDocker -RequireBuildx:(-not $SkipBuild)
    Write-CogitiaOk "Docker engine $($docker.Engine), compose $($docker.Compose)"
    Assert-CogitiaSources $registry
    Write-CogitiaOk 'Sources, Dockerfiles and compose file present'

    $secretsPath = Resolve-CogitiaPath $registry $envCfg.secrets_file
    if (-not (Test-Path $secretsPath)) {
        # Local convenience only: generate a local DB password once. Production never auto-generates.
        Write-CogitiaWarn "$($envCfg.secrets_file) not found -- creating it with a generated local POSTGRES_PASSWORD"
        Write-CogitiaLfFile $secretsPath @(
            '# Terra-Cogitia local secrets (generated by deploy-local.ps1, git-ignored).',
            "POSTGRES_PASSWORD=$(New-CogitiaPassword)",
            '# Required for AI features (theme/question generation, Discover):',
            'MISTRAL_API_KEY=')
    }
    $secrets = Read-CogitiaSecrets $secretsPath -Required @('POSTGRES_PASSWORD') -Optional @('MISTRAL_API_KEY', 'MISTRAL_MODEL', 'OPENAI_API_KEY')
    if (-not $secrets['MISTRAL_API_KEY']) {
        Write-CogitiaWarn "MISTRAL_API_KEY empty in $($envCfg.secrets_file): the stack runs, AI generation endpoints will fail"
    }
    Write-CogitiaOk "Secrets loaded from $($envCfg.secrets_file)"

    $services   = @(Get-CogitiaServices $registry)
    $containers = @($services | ForEach-Object { $_.Container })
    $runtimeDir = Join-Path (Resolve-CogitiaPath $registry $registry.paths.runtime_dir) 'local'
    $composeFile = Join-Path (Resolve-CogitiaPath $registry $registry.paths.docker_dir) 'docker-compose.yml'

    Write-Host ""
    Write-Host "  Containers: $($containers -join ', ')" -ForegroundColor Cyan
    Write-Host "  Network:    $($registry.network_name)" -ForegroundColor Cyan
    Write-Host "  Front-End:  $($envCfg.frontend_url)   Back-End: $($envCfg.api_base_url)" -ForegroundColor Cyan

    # --- Phase 2: Build ----------------------------------------------------------
    Write-CogitiaPhase 'PHASE 2: Build images'
    if ($SkipBuild) {
        Assert-CogitiaImagesExist $registry
        Write-CogitiaInfo 'SKIPPED (-SkipBuild): existing images found'
    } else {
        Build-CogitiaImages $registry -NoCache:$NoCache | Out-Null
    }

    # --- Phase 3: Runtime configuration ---------------------------------------
    Write-CogitiaPhase 'PHASE 3: Runtime configuration'
    $files = New-CogitiaRuntimeFiles -Registry $registry -EnvironmentName 'local' -OutDir $runtimeDir -Secrets $secrets
    Write-CogitiaOk "Generated $($files.Env)"
    Write-CogitiaOk "Generated $(Split-Path -Parent $files.Backend)\*.env"

    # --- Phase 4: Deploy ---------------------------------------------------------
    Write-CogitiaPhase 'PHASE 4: Deploy'
    if ($SkipBackup) { Write-CogitiaInfo 'Database backup SKIPPED (-SkipBackup)' } else { Backup-LocalDatabase }

    if ($null -eq (Get-CogitiaNetworkMembers $registry.network_name)) {
        Invoke-CogitiaNative docker @('network', 'create', '--label', $registry.image_label, $registry.network_name) -Quiet | Out-Null
        Write-CogitiaOk "Network $($registry.network_name) created"
    } else {
        Write-CogitiaOk "Network $($registry.network_name) already exists"
    }

    # Containers with our names but not owned by the compose project would block 'up' (name conflict).
    foreach ($c in $containers) {
        $owner = Invoke-CogitiaNative docker @('container', 'inspect', '-f', '{{json .Config.Labels}}', $c) -AllowFailure -Quiet
        if ($owner.ExitCode -ne 0) { continue }
        $labels = ($owner.Output -join '') | ConvertFrom-Json
        $project = if ($labels -and $labels.PSObject.Properties['com.docker.compose.project']) { $labels.'com.docker.compose.project' } else { '' }
        if ($project -ne $registry.compose_project) {
            Write-CogitiaWarn "Removing stray container $c (not managed by compose project '$($registry.compose_project)')"
            Invoke-CogitiaNative docker @('rm', '-f', $c) -Quiet | Out-Null
        }
    }

    Write-CogitiaStep 'docker compose up -d (recreates containers whose image or configuration changed)'
    Invoke-LocalCompose @('up', '-d', '--remove-orphans')

    # --- Phase 5: Health ---------------------------------------------------------
    Write-CogitiaPhase 'PHASE 5: Health'
    Wait-CogitiaHealthy -Containers $containers -TimeoutSec $HealthTimeoutSec

    # --- Phase 6: Verification ---------------------------------------------------
    Write-CogitiaPhase 'PHASE 6: Verification'
    $svc = $registry.services
    $checks = @()
    $checks += Get-CogitiaEndpointChecks -Registry $registry `
        -FrontendBase "http://localhost:$($svc.frontend.port)" -BackendBase "http://localhost:$($svc.backend.port)" `
        -ExpectedApiBaseUrl $envCfg.api_base_url -Origin $envCfg.frontend_url

    $members = Get-CogitiaNetworkMembers $registry.network_name
    if ($null -eq $members) { $members = @() }
    $missing = @($containers | Where-Object { $_ -notin $members })
    $checks += New-CogitiaCheck "All containers on $($registry.network_name)" ($missing.Count -eq 0) $(if ($missing) { "missing: $($missing -join ', ')" } else { $members -join ', ' })

    $net = Invoke-CogitiaNative docker @('exec', $svc.frontend.container_name, 'wget', '-q', '-O', '/dev/null', "http://$($svc.backend.alias):$($svc.backend.container_port)$($svc.backend.health_path)") -AllowFailure -Quiet
    $checks += New-CogitiaCheck 'Front-End -> Back-End via NetCogitia DNS' ($net.ExitCode -eq 0) "http://$($svc.backend.alias):$($svc.backend.container_port)"

    $dbNet = Invoke-CogitiaNative docker @('exec', $svc.backend.container_name, 'python', '-c', "import socket; socket.create_connection(('$($svc.database.alias)', $($svc.database.container_port)), 5)") -AllowFailure -Quiet
    $checks += New-CogitiaCheck 'Back-End -> Database via NetCogitia DNS' ($dbNet.ExitCode -eq 0) "$($svc.database.alias):$($svc.database.container_port)"

    foreach ($c in $containers) {
        $policy = (Invoke-CogitiaNative docker @('container', 'inspect', '-f', '{{.HostConfig.RestartPolicy.Name}}', $c) -Quiet).Output -join ''
        $checks += New-CogitiaCheck "Restart policy $c" ($policy -eq 'unless-stopped') $policy
    }
    $dbPorts = (Invoke-CogitiaNative docker @('port', $svc.database.container_name) -AllowFailure -Quiet).Output -join ' '
    $checks += New-CogitiaCheck 'Database not published on host' ([string]::IsNullOrWhiteSpace($dbPorts)) $(if ($dbPorts) { $dbPorts } else { 'internal only' })

    $failures = Write-CogitiaChecks $checks
    if ($failures -gt 0) { throw "$failures verification check(s) failed" }

    # --- Phase 7: Cleanup --------------------------------------------------------
    Write-CogitiaPhase 'PHASE 7: Cleanup (Terra-Cogitia dangling images only)'
    Invoke-CogitiaNative docker @('image', 'prune', '-f', '--filter', "label=$($registry.image_label)") | Out-Null

    Write-CogitiaBanner 'Local Deployment Succeeded'
    Write-Host "  Front-End:  $($envCfg.frontend_url)" -ForegroundColor Green
    Write-Host "  Back-End:   $($envCfg.api_base_url)  (docs: $($envCfg.api_base_url)/docs)" -ForegroundColor Green
}
catch {
    Write-Host ""
    Write-CogitiaFail $_.Exception.Message
    Write-Host "  Local deployment FAILED." -ForegroundColor Red
    $exitCode = 1
}
finally {
    Write-Host "  Total time: $([math]::Round(((Get-Date) - $overallStart).TotalMinutes, 1)) min" -ForegroundColor Cyan
    Write-Host ""
}
exit $exitCode
